# Generated by Django 4.1.2 on 2022-10-30 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prob_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.TextField(max_length=255)),
                ('p_level', models.CharField(choices=[('easy', 'EASY'), ('medium', 'MEDIUM'), ('hard', 'HARD')], default='easy', max_length=6)),
                ('p_link', models.URLField(max_length=255)),
                ('p_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems_app.prob_type')),
            ],
        ),
    ]
